services:
  go-fmt:
    image: ghcr.io/oullin/go-fmt:v0.1.0
    working_dir: /work
    volumes:
      - .:/work
    environment:
      HOST_PROJECT_PATH: ${PWD}
    entrypoint: ["/bin/sh", "-lc"]
    command:
      - trap 'exit 0' TERM INT; while :; do sleep 3600; done
