import type { RecommendationRecord } from "#store/types";

export const otherRecommendations = [
    {
        uuid: "a5029b3e-3ad2-45a4-8e98-2599cdf21697",
        relation: "Ross managed Gus directly.",
        text: "I had the pleasure of working alongside Gustavo for more than three years during his time at BeMyGuest.<br/><br/>Working within a tech team at a startup can be a very challenging experience, there are competing pressures to deliver new features as quickly as possible, whilst at the same time we have to work hard to maintain stability and quality within the code we produce.<br/><br/>Gustavo was an excellent and enthusiastic ambassador for this approach and led many initiatives to improve our systems, testing and architecture, leading to his work having a very positive impact on the overall quality of BeMyGuest's products.<br/><br/>I would highly recommend Gustavo, his combination of attention to detail, with an irrepressible drive to continue learning makes him a valuable asset within any software engineering team.",
        person: {
            avatar: "recommendation/ross-riley.jpeg",
            full_name: "Ross Riley",
            company: "BeMyGuest - Tours & Activities",
            designation: "CTO",
        },
        created_at: "2021-11-27",
        updated_at: "2021-11-27",
        featured: 1,
    },
    {
        uuid: "e4a9fd59-5ecf-467f-934a-798100478700",
        relation: "Ric worked with Gus in different teams.",
        text: "I had the pleasure of working with Gus for 1 year at BeMyGuest in Singapore. At the time our SAAS system was undergoing a number of new developments and Gus was extremely responsive and adaptable to deliver the continually changing needs of the end user.<br/><br/>Gus was a huge support during this period as he would not just deliver the tech but also ensure it was usable by our consumers. Extremely pleased to see him to continue develop and enhance his skills to be an excellent asset in any business.",
        person: {
            avatar: "recommendation/ric-corbett.jpeg",
            full_name: "Ric Corbett",
            company: "BeMyGuest - Tours & Activities",
            designation: "Director of Business Development",
        },
        created_at: "2021-11-12",
        updated_at: "2021-11-12",
        featured: 0,
    },
    {
        uuid: "6fa9fce8-f3a4-40ce-b87a-60134da50007",
        relation: "Daniel worked with Gus in different teams.",
        text: 'I am extremely pleased to write this letter of recommendation for Gustavo Ocanto and I have work together in the same company for the past 2 years and I found him a conscientious and a very hardworking individual.<br/><br/>Even though we are from different department, GUS have supported my side(BD) heaps on tech issue and troubleshoot instantly. In his role as an Engineering Lead he has gone beyond his Job Scope and will normally reach out to other in his own department to assist. Having GUS around in the company was fun and with his "slang" it makes us laugh hard at times.<br/><br/>During the years that I have cross path with GUS. I had the opportunity to observe his interpersonal style-he is pleasant and a positive motivator to his fellow team mates and colleagues.',
        person: {
            avatar: "recommendation/daniel-khor.jpeg",
            full_name: "Daniel Khor Chin Huat",
            company: "BeMyGuest - Tours & Activities",
            designation: "Director of Business Development",
        },
        created_at: "2021-10-27",
        updated_at: "2021-10-27",
        featured: 0,
    },
    {
        uuid: "1ca2026d-9d52-4da9-bbe2-5adba175d4c4",
        relation: "Kong worked with Gus in the same team.",
        text: "I have worked with Gus as a fellow Software Engineer since 2017. He is a highly adaptable, encouraging and supportive colleague and an effective team lead.<br/><br/>His software development skill, whether its backend, full stack, is of exceptional high quality. During our stint in the company, he took the time to spearhead some of the initiatives to improve and updating the software development process and applications.<br/><br/>He always has a positive attitude and a desire to produce quality work. Gus is as great a person as he was a colleague, a team lead and his next employer will be lucky to have him.",
        person: {
            avatar: "recommendation/kong-kw.jpg",
            full_name: "Kong KW",
            company: "BeMyGuest - Tours & Activities",
            designation: "Senior Software Engineer",
        },
        created_at: "2021-10-20",
        updated_at: "2021-10-20",
        featured: 0,
    },
    {
        uuid: "99d55cbb-11a4-4fd2-9d5a-1530ef9cb0bb",
        relation: "Wai Min worked with Gus in different teams.",
        text: "I've had the opportunity of knowing Gus for the past. He is always capable of adapting to new working environments. Very positive attitude towards work I definitely would recommend him as full stack web developer.",
        person: {
            avatar: "recommendation/wai-min.jpeg",
            full_name: "Wai Min Ho",
            company: "BeMyGuest - Tours & Activities",
            designation: "Distribution Partnerships Manager",
        },
        created_at: "2020-10-16",
        updated_at: "2020-10-16",
        featured: 0,
    },
    {
        uuid: "baf49d10-1700-4881-9268-5076e80f42f5",
        relation: "Daryle worked with Gus in the same team.",
        text: "I've had the opportunity of knowing Gus for the past. He is always capable of adapting to new working environments. Very positive attitude towards work I definitely would recommend him as full stack web developer.",
        person: {
            avatar: "recommendation/daryle-dale-silva.jpeg",
            full_name: "Daryle Dale De Silva",
            company: "BeMyGuest - Tours & Activities",
            designation: "Senior Full Stack Developer",
        },
        created_at: "2020-01-19",
        updated_at: "2020-01-19",
        featured: 0,
    },
    {
        uuid: "3fb5dfaa-a7b7-411c-8d2e-80b75fcd45df",
        relation: "Dawid managed Gus directly.",
        text: "It was a pleasure to have an opportunity to work with Gustavo. He's a brilliant developer and analyst, with a head full of new ideas. He's not afraid of approaching the most complex problems and testing new waters to find the best solutions.<br/><br/>He's got a great personality and always fun to have around in your team. Always keen to share his knowledge thru training or giving public presentations. He's got that deep internal drive to learn every day and test new ideas in real life, which I always find very valuable.",
        person: {
            avatar: "recommendation/dawid-makowski.jpeg",
            full_name: "Dawid Makowski",
            company: "BeMyGuest - Tours & Activities",
            designation: "CTO",
        },
        created_at: "2019-07-16",
        updated_at: "2019-07-16",
        featured: 1,
    },
    {
        uuid: "045ff8fc-12af-47c7-a761-6c2a0995d352",
        relation: "Jarek managed Gus indirectly",
        text: "Gus has been always committed and eager to learn on professional level plus an exceptional personality when it comes to socializing, which made him a great and valuable team member during our time together at BeMyGuest in Singapore.<br/><br/>Can't recommend enough!",
        person: {
            avatar: "recommendation/jarek-tkaczyk.jpeg",
            full_name: "Jarek Tkaczyk",
            company: "BeMyGuest - Tours & Activities",
            designation: "Tech Lead",
        },
        created_at: "2019-07-11",
        updated_at: "2019-07-11",
        featured: 0,
    },
    {
        uuid: "4784b603-583d-4159-ab6b-7e7bddb4b3e5",
        relation: "Clement managed Gus indirectly",
        text: "Very driven and out of the box thinker, coming up with innovative solutions to complex tech problems! Totally enjoyed having him on the team!",
        person: {
            avatar: "recommendation/clement-wong.jpeg",
            full_name: "Clement Wong",
            company: "BeMyGuest - Tours & Activities",
            designation: "CEO",
        },
        created_at: "2019-06-15",
        updated_at: "2019-06-15",
        featured: 1,
    },
    {
        uuid: "1991f645-d50a-4975-8ba6-90cf18ae3a90",
        relation: "Rudolf worked with Gus in the same team.",
        text: "It is been a real pleasure working together with Gustavo. He's motivated, filled with knowledge, great at public speaking, especially about PHP, Unit Testing or Laravel itself. He worked on biggest projects, properly taking care of the job.<br/><br/>Hard working, responsible and ambitious. Definitely worth recommending.",
        person: {
            avatar: "recommendation/rudolf-ratusiski.jpeg",
            full_name: "Rudolf Ratusiński",
            company: "BeMyGuest - Tours & Activities",
            designation: "Senior DevOps Engineer",
        },
        created_at: "2019-06-14",
        updated_at: "2019-06-14",
        featured: 0,
    },
    {
        uuid: "186c98c0-9df5-42c2-bccd-3724e4f50917",
        relation: "Nabil worked with Gus in different teams.",
        text: "Gustavo is a team player, tech enthusiast with very positive energy.gustavo is one of those colleagues that makes you enjoy working more at the office, he is creative, fast learner and hard worker.",
        person: {
            avatar: "recommendation/nabil-elshafaey.jpeg",
            full_name: "Nabil Elshafaey",
            company: "BeMyGuest - Tours & Activities",
            designation: "Head of Distribution",
        },
        created_at: "2019-06-13",
        updated_at: "2019-06-13",
        featured: 0,
    },
    {
        uuid: "9410aaec-c4fe-4078-ae84-ab2d2dee19d9",
        relation: "Sophie reported directly to Gus.",
        text: "Gus is the one who's really enthusiastic about tech regardless of back-end or front-end. With the pursuit of code quality, he keeps polishing tech skills as well as being very active for code review.<br/><br/>Meanwhile, he enjoys sharing his findings in public and we all benefited a lot from it.",
        person: {
            avatar: "recommendation/sophie-ha.jpeg",
            full_name: "Sophie Ha",
            company: "BeMyGuest - Tours & Activities",
            designation: "Software Engineer",
        },
        created_at: "2019-05-31",
        updated_at: "2019-05-31",
        featured: 0,
    },
    {
        uuid: "d7839355-c7af-4962-bcbd-e7f41a75199c",
        relation: "Sohail worked with Gus in the same team.",
        text: "I'm enjoying a pleasure of working alongside Gustavo for a year now. He has high work ethics and great experience in web technologies to the level that BeMyGuest entrusted him in handling challenging problems (i.e. payment gateways in fragmented South East Asia, API integration, Test Driven Development, Continuous Integration, and Continuous Delivery).<br/><br/>But that is not all, Gustavo regardless of deadline pressure always delivers with a smile. His sense of humor always softens the toughest stressful situations for the rest of the team. \nLong story short he is a true asset to our team.",
        person: {
            avatar: "recommendation/sohail-salehi.jpeg",
            full_name: "Sohail Salehi",
            company: "BeMyGuest - Tours & Activities",
            designation: "Senior Software Engineer",
        },
        created_at: "2018-09-26",
        updated_at: "2018-09-26",
        featured: 0,
    },
    {
        uuid: "0f6dae3e-ec78-43a9-b9ff-322642f88594",
        relation: "Michal worked with Gus in the same team.",
        text: "I had a chance to collaborate with Gustavo for one year, working at one team. He impressed me with his openness and willingness to learn. He dig deeper and deeper in subjects he already knew.<br/><br/>He was also great in sharing that knowledge. Best social skills across all developers I’ve ever meet. Perfect fit to 10xTeam.",
        person: {
            avatar: "recommendation/michal-szymaniak.jpeg",
            full_name: "Michal Szymaniak",
            company: "BeMyGuest - Tours & Activities",
            designation: "Senior Software Engineer",
        },
        created_at: "2018-09-26",
        updated_at: "2018-09-26",
        featured: 0,
    },
    {
        uuid: "387a95d6-d29b-4faf-aa60-3b071c59cd22",
        relation: "Fernando worked with Gus but they were at different companies.",
        text: "I have had the opportunity to work with Gustavo closely and he has demonstrated to be a skilled person. Focus on detail and solid principles. He is a learner by definition and strives for improvement on every step.<br/><br/>Our two projects turned out to be more productive than we forecasted at the beginning of them and I personally can recommend Gustavo as a reliable professional to work with.",
        person: {
            avatar: "recommendation/fernando-rivas.jpeg",
            full_name: "Fernando Rivas",
            company: "Websarrollo - Digital Agency",
            designation: "Senior Software Engineer",
        },
        created_at: "2018-08-30",
        updated_at: "2018-08-30",
        featured: 0,
    },
    {
        uuid: "8e05af84-3054-404f-89f2-428ae69943ef",
        relation: "Jonathan worked with Gus but they were at different companies.",
        text: "Excellent programmer and good project manager with good creative ideas. A good experience to have worked with him.",
        person: {
            avatar: "recommendation/jonathan-trejo.jpeg",
            full_name: "Jonathan Ivan Trejo Zerpa",
            company: "Websarrollo - Digital Agency",
            designation: "Senior Software Engineer",
        },
        created_at: "2018-08-28",
        updated_at: "2018-08-28",
        featured: 0,
    },
    {
        uuid: "4faf4435-93d4-48ef-b980-4b94d353f2f7",
        relation: "Carlos Matute worked with Gus but they were at different companies.",
        text: "I can say that Gustavo had a professional level raising even since we studied at the University. Dedicated, spontaneous, with a very wide resolution of problems and with determination in the solutions due to his high knowledge in the workplace.",
        person: {
            avatar: "recommendation/carlos-matute.jpeg",
            full_name: "Carlos Matute",
            company: "Websarrollo - Digital Agency",
            designation: "Senior Software Engineer",
        },
        created_at: "2018-08-27",
        updated_at: "2018-08-27",
        featured: 0,
    },
    {
        uuid: "50fcd53c-2135-4c94-8fb2-30f111b3218e",
        relation: "Julio Cesar reported directly to Gus.",
        text: "I recommend Gustavo for large projects. He is a professional in the development area very proactive and efficient. It makes use of all the tools available for project management. It is organized and possesses determination and mastery over the development team.",
        person: {
            avatar: "recommendation/julio-cesar.png",
            full_name: "Julio Cesar Hernandez",
            company: "Websarrollo - Digital Agency",
            designation: "Senior Software Engineer",
        },
        created_at: "2018-08-27",
        updated_at: "2018-08-27",
        featured: 0,
    },
    {
        uuid: "b5b4cff9-156e-4296-974e-0c4f0437e31d",
        relation: "Marco work with Gus in the same team.",
        text: "Professional worker, fast learner, enjoyable to work with. Highly analyzer of low level code, always approaching methodology with security first.",
        person: {
            avatar: "recommendation/marco.jpeg",
            full_name: "Marco Gava",
            company: "BeMyGuest - Tours & Activities",
            designation: "Senior Software Engineer",
        },
        created_at: "2018-08-27",
        updated_at: "2018-08-27",
        featured: 0,
    },
] as const satisfies readonly RecommendationRecord[];
