import type { RecommendationRecord } from "../types";

export const perxRecommendations = [
    {
        uuid: "be1f8226-61d8-4b9b-a30f-0cdb521bd841",
        relation: "Grant reported to Gus directly.",
        text: "Gus was an exceptional manager who truly valued his people. He led with empathy, clarity, and consistency - qualities that made our team stronger and more motivated. I’m grateful for his mentorship and would gladly work with him again.",
        person: {
            avatar: "recommendation/grant-riggle.jpeg",
            full_name: "Grant Riggle",
            company: "Perx Technologies",
            designation: "Solutions Architect",
        },
        created_at: "2025-10-20",
        updated_at: "2025-10-20",
        featured: 1,
    },
    {
        uuid: "0fa21471-c13a-4c8a-83ba-9b5d8782ab72",
        relation: "Amen managed Gus directly.",
        text: "I've had the pleasure of interacting with Gus on several occasions and have consistently been impressed by his strong technical acumen, effective leadership, and collaborative spirit. Gus adeptly manages diverse engineering teams, including DevOps, Infrastructure, Data, Frontend, Backend, and Support.<br/><br/>He excels at optimizing performance, streamlining operations, and fostering clear, productive communication across global teams. Gus is a true asset, and I highly recommend him for any senior engineering leadership role.",
        person: {
            avatar: "recommendation/amen-reghimi.png",
            full_name: "Amenallah Reghimi",
            company: "Perx Technologies",
            designation: "CTO / Board Director",
        },
        created_at: "2025-05-25",
        updated_at: "2025-05-25",
        featured: 1,
    },
    {
        uuid: "4375e073-9098-4f5f-9f8b-44ca47667f0b",
        relation: "Lakshey worked with Gus in the same team.",
        text: "Working with Gustavo at Perx Technologies fundamentally reshaped how I view great technical leadership. What set him apart wasn’t just technical depth, it was the way they made engineering a strategic advantage for the business. He is excellent in aligning product, engineering, and business stakeholders around a shared roadmap, which reduced cross-team friction and accelerated time-to-market.<br/><br/>Beyond the tech, they built a culture of ownership and psychological safety within the engineering org. Teams trusted their judgment because it was always backed by clarity, consistency, and data, not noise.<br/><br/>Any company looking to turn engineering into a true strategic function and not just a delivery engine, would be lucky to have him.",
        person: {
            avatar: "recommendation/lakshey-perx.jpeg",
            full_name: "Lakshey Singhal",
            company: "Perx Technologies",
            designation: "Senior Project Manager",
        },
        created_at: "2025-04-30",
        updated_at: "2025-04-30",
        featured: 0,
    },
    {
        uuid: "7dc74d20-42e1-4f09-9c8d-20ecfc6caad7",
        relation: "Amrith worked with Gus in the same team.",
        text: "Gus and I were peers at Perx during his tenure as Head of Engineering. He led several key initiatives, including scaling the engineering team and aligning cross-functional efforts across DevOps, backend, frontend, and data. Additionally, he drove projects focused on infrastructure modernisation, performance optimisation, and cloud cost efficiency.<br/><br/>He's a hands-on and technically strong leader who enjoys solving complex engineering problems. Outside of work, Gustavo is highly disciplined when it comes to health and fitness, always consistent and focused, which says a lot about his overall approach to life and work.",
        person: {
            avatar: "recommendation/amrith-g.jpeg",
            full_name: "Amrith G",
            company: "Perx Technologies",
            designation: "Head of Marketing",
        },
        created_at: "2025-03-26",
        updated_at: "2025-03-26",
        featured: 0,
    },
    {
        uuid: "68d753fa-e523-4c68-a3f3-944bfee52e44",
        relation: "Gus was Rob's client.",
        text: "I had the pleasure of working with Gus at Perx Technologies from June 2024 to March 2025, where I served as a consultant on platform infrastructure while he led the engineering team.<br/><br/>Gus's passion for the product and unwavering work ethic pushed the team forward through difficult technical challenges. His straightforward approach and commitment to getting things done, even in high-pressure situations, demonstrated his resilience as a leader.<br/><br/>Any organization facing tough engineering challenges would benefit from Gus's determination and technical grit.",
        person: {
            avatar: "recommendation/rob-roach.jpeg",
            full_name: "Rob Roach",
            company: "Perx Technologies",
            designation: "Infrastructure Solutions Vendor",
        },
        created_at: "2025-03-10",
        updated_at: "2025-03-10",
        featured: 1,
    },
    {
        uuid: "2eed9ce3-2c48-4b06-9dfc-9fc3a2c75f01",
        relation: "Guillem reported to Gus directly.",
        text: "I had the privilege of working with Gus for the past twelve months, during which he demonstrated genuine care and unwavering dedication to our team's success.<br/><br/>He consistently prioritised our well-being and professional growth, fostering an environment where everyone felt valued. Gus spearheaded significant improvements in our engineering processes, streamlining workflows, developing comprehensive documentation and enhancing efficiency.",
        person: {
            avatar: "recommendation/guillem-roma.jpeg",
            full_name: "Guillem Roma",
            company: "Perx Technologies",
            designation: "Tech Lead",
        },
        created_at: "2025-03-09",
        updated_at: "2025-03-09",
        featured: 0,
    },
    {
        uuid: "fcf927e0-e8ab-4c4b-adfa-65ecfcf902de",
        relation: "Waseem reported to Gus directly.",
        text: " I had the privilege of working under Gus’s leadership at Perx, and his impact on our team was truly remarkable. He has a strategic approach to process optimization, always focusing on long-term efficiency rather than just quick fixes. His improvements in workflows, documentation, and monitoring significantly enhanced our software quality and delivery.<br/><br/>What sets Gus apart is his leadership style, he provides clear direction while trusting his team to work independently. His support and guidance through regular check-ins create an environment where developers feel empowered and motivated. Additionally, his ability to bridge gaps between product and engineering strengthened cross-team collaboration, driving overall success.<br/><br/>Gus is a leader who not only optimizes processes but also elevates the people around him. I highly recommend him for any role where expertise, innovation, and leadership are key.",
        person: {
            avatar: "recommendation/waseem-hakeem.jpeg",
            full_name: "Waseem Hakeem",
            company: "Perx Technologies",
            designation: "Software Engineer",
        },
        created_at: "2025-03-06",
        updated_at: "2025-03-06",
        featured: 0,
    },
    {
        uuid: "86fa5273-4e21-45e0-80de-5ec908cf6f81",
        relation: "Bhupesh reported directly to Gus.",
        text: "I had the privilege of working under Gustavo as an Engineering Manager, and his leadership has been nothing short of inspiring. Not only does he bring exceptional technical expertise and strategic thinking, but he also leads with empathy—something that truly sets him apart.<br/><br/>Gustavo doesn’t just manage a team; he genuinely cares about each individual’s growth, challenges, and well-being. He understands the personal and professional struggles employees face and goes above and beyond to support them. This ability to balance technical excellence with emotional intelligence creates a culture of trust, collaboration, and high performance.<br/><br/>His problem-solving mindset, clear communication, and mentorship have had a lasting impact on both the team and the success of our projects. Working with him has been a learning experience, and I highly recommend him to any organization looking for a strong, people-focused engineering leader.",
        person: {
            avatar: "recommendation/bhupesh-pathak.jpeg",
            full_name: "Bhupesh Pathak",
            company: "Perx Technologies",
            designation: "Senior Software Engineer",
        },
        created_at: "2025-02-26",
        updated_at: "2025-02-26",
        featured: 0,
    },
    {
        uuid: "dec7e524-34cc-405c-9b3a-01999852c9bb",
        relation: "Victory reported directly to Gus.",
        text: "I had a chance to work with Gus at Perx for the last 9 months. He consistently guided the team with clarity and supported our professional growth.<br/><br/>Despite the challenges posed by an unclear structure and team dynamics, Gus has been dedicated to making processes smoother and more consistent across departments.<br/><br/>His efforts to foster collaboration and improve workflows have had a meaningful impact on the team. I highly recommend Gus as a capable and inspiring engineering leader.",
        person: {
            avatar: "recommendation/victory-sometime.jpeg",
            full_name: "Victory SOMETIME",
            company: "Perx Technologies",
            designation: "Senior Software Engineer",
        },
        created_at: "2025-02-19",
        updated_at: "2025-02-19",
        featured: 0,
    },
] as const satisfies readonly RecommendationRecord[];
