import type { RecommendationsFixture } from "./types";

export const recommendations = {
    version: "1.0.7",
    data: [
        {
            uuid: "1f58646c-ba87-4306-905f-cb64a5e49b5e",
            relation: "Shaun Chan reported to Gus directly.",
            text: "I had the pleasure of working with Gus, and it was an absolute joy. He’s an incredibly technical and knowledgeable developer with a natural ability to make complex topics approachable. Gus consistently maintains high standards in his work and always delivers projects on time.<br/><br/>What really sets him apart is his eagerness to learn new technologies and his generosity in sharing that knowledge with others. He’s been an amazing mentor and a true team player. Any team would be lucky to have someone as dedicated, skilled, and collaborative as Gus.",
            person: {
                avatar: "recommendation/shaun-chan.jpeg",
                full_name: "Shaun Chan",
                company: "Silverlake",
                designation: "Software Engineer",
            },
            created_at: "2025-11-07",
            updated_at: "2025-11-07",
            featured: 0,
        },
        {
            uuid: "ae960c59-4715-49d5-8a67-0b2464b79c26",
            relation: "Wan Ting reported to Gus directly.",
            text: "Gust is a highly skilled full-stack developer, technical lead, and architect with deep expertise in building scalable, secure solutions—critical in the fast-paced fintech landscape. Beyond his technical acumen, Gust is a generous mentor who actively shares knowledge, identifies blind spots, and encourages continuous learning.<br/><br/>His guidance helped our team navigate complex challenges and sharpen our strategic thinking, both in product development and career growth.<br/><br/>I'm grateful to have had such a thoughtful and visionary leader on our team.",
            person: {
                avatar: "recommendation/wan-ting.jpeg",
                full_name: "Wan Ting",
                company: "Silverlake",
                designation: "Software Engineer",
            },
            created_at: "2025-11-06",
            updated_at: "2025-11-06",
            featured: 0,
        },
        {
            uuid: "d73e4610-a636-41e4-974f-a294abdd1a72",
            relation: "Hooi Yang reported to Gus directly.",
            text: "I’m extremely lucky to be able to work with Gus. He’s a friendly, approachable person who’s genuinely easy to be around, while also being an elite professional who knows his craft inside and out. At work he strives for excellence in everything he does and communicates with clarity and purpose.<br/><br/>Eager to stay the top of the game, Gus is always learning and exploring new technologies. More importantly, he shares his valuable knowledge and experience with me. As a natural leader, he inspires those around him to be self-improve and be better. I've learnt a lot from him and highly recommend him.",
            person: {
                avatar: "recommendation/felix-silverlake.jpeg",
                full_name: "Hooi Yang Choo",
                company: "Silverlake",
                designation: "Software Engineer",
            },
            created_at: "2025-11-04",
            updated_at: "2025-11-04",
            featured: 0,
        },
        {
            uuid: "be1f8226-61d8-4b9b-a30f-0cdb521bd841",
            relation: "Grant reported to Gus directly.",
            text: "Gus was an exceptional manager who truly valued his people. He led with empathy, clarity, and consistency - qualities that made our team stronger and more motivated. I’m grateful for his mentorship and would gladly work with him again.",
            person: {
                avatar: "recommendation/grant-riggle.jpeg",
                full_name: "Grant Riggle",
                company: "Perx Technologies",
                designation: "Solutions Architect",
            },
            created_at: "2025-10-20",
            updated_at: "2025-10-20",
            featured: 1,
        },
        {
            uuid: "0fa21471-c13a-4c8a-83ba-9b5d8782ab72",
            relation: "Amen managed Gus directly.",
            text: "I've had the pleasure of interacting with Gus on several occasions and have consistently been impressed by his strong technical acumen, effective leadership, and collaborative spirit. Gus adeptly manages diverse engineering teams, including DevOps, Infrastructure, Data, Frontend, Backend, and Support.<br/><br/>He excels at optimizing performance, streamlining operations, and fostering clear, productive communication across global teams. Gus is a true asset, and I highly recommend him for any senior engineering leadership role.",
            person: {
                avatar: "recommendation/amen-reghimi.png",
                full_name: "Amenallah Reghimi",
                company: "Perx Technologies",
                designation: "CTO / Board Director",
            },
            created_at: "2025-05-25",
            updated_at: "2025-05-25",
            featured: 1,
        },
        {
            uuid: "4375e073-9098-4f5f-9f8b-44ca47667f0b",
            relation: "Lakshey worked with Gus in the same team.",
            text: "Working with Gustavo at Perx Technologies fundamentally reshaped how I view great technical leadership. What set him apart wasn’t just technical depth, it was the way they made engineering a strategic advantage for the business. He is excellent in aligning product, engineering, and business stakeholders around a shared roadmap, which reduced cross-team friction and accelerated time-to-market.<br/><br/>Beyond the tech, they built a culture of ownership and psychological safety within the engineering org. Teams trusted their judgment because it was always backed by clarity, consistency, and data, not noise.<br/><br/>Any company looking to turn engineering into a true strategic function and not just a delivery engine, would be lucky to have him.",
            person: {
                avatar: "recommendation/lakshey-perx.jpeg",
                full_name: "Lakshey Singhal",
                company: "Perx Technologies",
                designation: "Senior Project Manager",
            },
            created_at: "2025-04-30",
            updated_at: "2025-04-30",
            featured: 0,
        },
        {
            uuid: "7dc74d20-42e1-4f09-9c8d-20ecfc6caad7",
            relation: "Amrith worked with Gus in the same team.",
            text: "Gus and I were peers at Perx during his tenure as Head of Engineering. He led several key initiatives, including scaling the engineering team and aligning cross-functional efforts across DevOps, backend, frontend, and data. Additionally, he drove projects focused on infrastructure modernisation, performance optimisation, and cloud cost efficiency.<br/><br/>He's a hands-on and technically strong leader who enjoys solving complex engineering problems. Outside of work, Gustavo is highly disciplined when it comes to health and fitness, always consistent and focused, which says a lot about his overall approach to life and work.",
            person: {
                avatar: "recommendation/amrith-g.jpeg",
                full_name: "Amrith G",
                company: "Perx Technologies",
                designation: "Head of Marketing",
            },
            created_at: "2025-03-26",
            updated_at: "2025-03-26",
            featured: 0,
        },
        {
            uuid: "68d753fa-e523-4c68-a3f3-944bfee52e44",
            relation: "Gus was Rob's client.",
            text: "I had the pleasure of working with Gus at Perx Technologies from June 2024 to March 2025, where I served as a consultant on platform infrastructure while he led the engineering team.<br/><br/>Gus's passion for the product and unwavering work ethic pushed the team forward through difficult technical challenges. His straightforward approach and commitment to getting things done, even in high-pressure situations, demonstrated his resilience as a leader.<br/><br/>Any organization facing tough engineering challenges would benefit from Gus's determination and technical grit.",
            person: {
                avatar: "recommendation/rob-roach.jpeg",
                full_name: "Rob Roach",
                company: "Perx Technologies",
                designation: "Infrastructure Solutions Vendor",
            },
            created_at: "2025-03-10",
            updated_at: "2025-03-10",
            featured: 1,
        },
        {
            uuid: "2eed9ce3-2c48-4b06-9dfc-9fc3a2c75f01",
            relation: "Guillem reported to Gus directly.",
            text: "I had the privilege of working with Gus for the past twelve months, during which he demonstrated genuine care and unwavering dedication to our team's success.<br/><br/>He consistently prioritised our well-being and professional growth, fostering an environment where everyone felt valued. Gus spearheaded significant improvements in our engineering processes, streamlining workflows, developing comprehensive documentation and enhancing efficiency.",
            person: {
                avatar: "recommendation/guillem-roma.jpeg",
                full_name: "Guillem Roma",
                company: "Perx Technologies",
                designation: "Tech Lead",
            },
            created_at: "2025-03-09",
            updated_at: "2025-03-09",
            featured: 0,
        },
        {
            uuid: "fcf927e0-e8ab-4c4b-adfa-65ecfcf902de",
            relation: "Waseem reported to Gus directly.",
            text: " I had the privilege of working under Gus’s leadership at Perx, and his impact on our team was truly remarkable. He has a strategic approach to process optimization, always focusing on long-term efficiency rather than just quick fixes. His improvements in workflows, documentation, and monitoring significantly enhanced our software quality and delivery.<br/><br/>What sets Gus apart is his leadership style, he provides clear direction while trusting his team to work independently. His support and guidance through regular check-ins create an environment where developers feel empowered and motivated. Additionally, his ability to bridge gaps between product and engineering strengthened cross-team collaboration, driving overall success.<br/><br/>Gus is a leader who not only optimizes processes but also elevates the people around him. I highly recommend him for any role where expertise, innovation, and leadership are key.",
            person: {
                avatar: "recommendation/waseem-hakeem.jpeg",
                full_name: "Waseem Hakeem",
                company: "Perx Technologies",
                designation: "Software Engineer",
            },
            created_at: "2025-03-06",
            updated_at: "2025-03-06",
            featured: 0,
        },
        {
            uuid: "86fa5273-4e21-45e0-80de-5ec908cf6f81",
            relation: "Bhupesh reported directly to Gus.",
            text: "I had the privilege of working under Gustavo as an Engineering Manager, and his leadership has been nothing short of inspiring. Not only does he bring exceptional technical expertise and strategic thinking, but he also leads with empathy—something that truly sets him apart.<br/><br/>Gustavo doesn’t just manage a team; he genuinely cares about each individual’s growth, challenges, and well-being. He understands the personal and professional struggles employees face and goes above and beyond to support them. This ability to balance technical excellence with emotional intelligence creates a culture of trust, collaboration, and high performance.<br/><br/>His problem-solving mindset, clear communication, and mentorship have had a lasting impact on both the team and the success of our projects. Working with him has been a learning experience, and I highly recommend him to any organization looking for a strong, people-focused engineering leader.",
            person: {
                avatar: "recommendation/bhupesh-pathak.jpeg",
                full_name: "Bhupesh Pathak",
                company: "Perx Technologies",
                designation: "Senior Software Engineer",
            },
            created_at: "2025-02-26",
            updated_at: "2025-02-26",
            featured: 0,
        },
        {
            uuid: "dec7e524-34cc-405c-9b3a-01999852c9bb",
            relation: "Victory reported directly to Gus.",
            text: "I had a chance to work with Gus at Perx for the last 9 months. He consistently guided the team with clarity and supported our professional growth.<br/><br/>Despite the challenges posed by an unclear structure and team dynamics, Gus has been dedicated to making processes smoother and more consistent across departments.<br/><br/>His efforts to foster collaboration and improve workflows have had a meaningful impact on the team. I highly recommend Gus as a capable and inspiring engineering leader.",
            person: {
                avatar: "recommendation/victory-sometime.jpeg",
                full_name: "Victory SOMETIME",
                company: "Perx Technologies",
                designation: "Senior Software Engineer",
            },
            created_at: "2025-02-19",
            updated_at: "2025-02-19",
            featured: 0,
        },
        {
            uuid: "e4626228-99fa-4778-9a22-783174e7ab60",
            relation: "Damien was a senior to Gus, but did not manage him directly.",
            text: "Over the past two years, Gus has shown consistently high levels of technical skill and an innovative mindset, adapting through numerous changes and growth periods within our company.<br/><br/>He is always eager to support the team in reaching its goals, displaying readiness to take action, and effective communication. His ability to think outside the box is a distinct strength.<br/><br/>In this time, he also worked intentionally on his planning and leadership abilities, which have significantly complemented his already notable contributions to the team.",
            person: {
                avatar: "recommendation/damien-passavent.jpeg",
                full_name: "Damien Passavent",
                company: "Aspire",
                designation: "Chief Product Officer",
            },
            created_at: "2024-04-10",
            updated_at: "2024-04-10",
            featured: 1,
        },
        {
            uuid: "fa5c4084-e1b4-45dd-a314-e8d9f589f67e",
            relation: "Claudio managed Gus directly.",
            text: "Gustavo's blend of strong technical skills, problem-solving, and warm personality make him stand out. He's not only great at leading projects but also shines in teamwork, often stepping beyond his role to help others.<br/><br/>As a mentor, he'd be invaluable, and his ability to communicate and innovate positions him perfectly for roles that bridge technical teams and clients.",
            person: {
                avatar: "recommendation/claudio-reggiani.jpeg",
                full_name: "Claudio Reggiani",
                company: "Aspire",
                designation: "Engineering Manger",
            },
            created_at: "2024-04-10",
            updated_at: "2024-04-10",
            featured: 1,
        },
        {
            uuid: "8bc18bf9-0983-4c7e-8095-b3d1e642fee4",
            relation: "Yash worked with Gus in the same team.",
            text: "I had the pleasure of closely collaborating with Gustavo during my tenure as a Product Manager in the Payments squad in Aspire where he was the Engineering Manager. Throughout our partnership on various high-priority and critical projects, Gustavo's leadership not only ensured that the development team was aligned with project goals but also served as a driving force for inspiring excellence.<br/><br/>Gustavo's dedication to the technical aspects of our work and his openness to feedback were truly commendable. He actively contributed to problem solving discussions, demonstrating a commitment to continuous improvement. These qualities had a profound impact on the success of the products and features that we built together.",
            person: {
                avatar: "recommendation/yash-aspire.jpeg",
                full_name: "Yash Maheshwari",
                company: "Aspire",
                designation: "Senior Product Manager",
            },
            created_at: "2023-11-28",
            updated_at: "2023-11-28",
            featured: 0,
        },
        {
            uuid: "b282a643-b283-41be-82ee-5a3eda853e69",
            relation: "Mohin worked with Gus in the same team.",
            text: "Gustavo is a highly skilled web developer with special expertise in PHP, GoLang, and a bunch of other languages along with extensive experience in managing large-scale distributed systems.<br/><br/>During our collaboration, Gustavo showcased exceptional problem-solving abilities, ensuring the highest standards of code quality and performance. He is not only technically proficient but also a great team player, always ready to share knowledge and support colleagues and a great asset to the team.",
            person: {
                avatar: "recommendation/mohin-lakdawala.jpeg",
                full_name: "Mohin Lakdawala",
                company: "Aspire",
                designation: "Senior Software Engineer",
            },
            created_at: "2023-10-19",
            updated_at: "2023-10-19",
            featured: 0,
        },
        {
            uuid: "0e587fa2-b678-4ca5-9eed-0f115c4a092d",
            relation: "Jarek managed Gus indirectly.",
            text: "I have worked with Gustavo as a Sr Engineer in my department at Aspire. It was the second time we worked together and it has been a great pleasure to see how far Gustavo progressed in the last few years.<br/><br/>Gustavo has an exceptional depth of knowledge in software development and consistently expands his high-quality knowledge with new technologies to better fit scaling team and systems.<br/><br/>He constantly demonstrated ambition and drive to learn and improve each stage of the engineering process. With his level of knowledge and skills I can wholeheartedly recommend Gustavo for senior technical roles, as well as leadership positions where he can leverage this experience even more.",
            person: {
                avatar: "recommendation/jarek-tkaczyk.jpeg",
                full_name: "Jarek Tkaczyk",
                company: "Aspire",
                designation: "Head of Engineering",
            },
            created_at: "2023-02-27",
            updated_at: "2023-02-27",
            featured: 1,
        },
        {
            uuid: "4b4d927a-ad7b-4f00-9140-d5b27f99fdc9",
            relation: "Rajan reported to Gus directly.",
            text: "I worked with Gustavo in the same team for Aspire. He had excellent time management skills and had a knack for keeping everyone calm and productive during intense crunch periods. His work ethics is immaculate and so easy to work together with. Also he goes out of his way when you ask for some help and guidance. Any company would be lucky to have Gustavo.",
            person: {
                avatar: "recommendation/rajan-chaudhary.jpeg",
                full_name: "Rajan Chaudhary",
                company: "Aspire",
                designation: "Senior QA Engineer",
            },
            created_at: "2022-11-16",
            updated_at: "2022-11-16",
            featured: 0,
        },
        {
            uuid: "a5029b3e-3ad2-45a4-8e98-2599cdf21697",
            relation: "Ross managed Gus directly.",
            text: "I had the pleasure of working alongside Gustavo for more than three years during his time at BeMyGuest.<br/><br/>Working within a tech team at a startup can be a very challenging experience, there are competing pressures to deliver new features as quickly as possible, whilst at the same time we have to work hard to maintain stability and quality within the code we produce.<br/><br/>Gustavo was an excellent and enthusiastic ambassador for this approach and led many initiatives to improve our systems, testing and architecture, leading to his work having a very positive impact on the overall quality of BeMyGuest's products.<br/><br/>I would highly recommend Gustavo, his combination of attention to detail, with an irrepressible drive to continue learning makes him a valuable asset within any software engineering team.",
            person: {
                avatar: "recommendation/ross-riley.jpeg",
                full_name: "Ross Riley",
                company: "BeMyGuest - Tours & Activities",
                designation: "CTO",
            },
            created_at: "2021-11-27",
            updated_at: "2021-11-27",
            featured: 1,
        },
        {
            uuid: "e4a9fd59-5ecf-467f-934a-798100478700",
            relation: "Ric worked with Gus in different teams.",
            text: "I had the pleasure of working with Gus for 1 year at BeMyGuest in Singapore. At the time our SAAS system was undergoing a number of new developments and Gus was extremely responsive and adaptable to deliver the continually changing needs of the end user.<br/><br/>Gus was a huge support during this period as he would not just deliver the tech but also ensure it was usable by our consumers. Extremely pleased to see him to continue develop and enhance his skills to be an excellent asset in any business.",
            person: {
                avatar: "recommendation/ric-corbett.jpeg",
                full_name: "Ric Corbett",
                company: "BeMyGuest - Tours & Activities",
                designation: "Director of Business Development",
            },
            created_at: "2021-11-12",
            updated_at: "2021-11-12",
            featured: 0,
        },
        {
            uuid: "6fa9fce8-f3a4-40ce-b87a-60134da50007",
            relation: "Daniel worked with Gus in different teams.",
            text: 'I am extremely pleased to write this letter of recommendation for Gustavo Ocanto and I have work together in the same company for the past 2 years and I found him a conscientious and a very hardworking individual.<br/><br/>Even though we are from different department, GUS have supported my side(BD) heaps on tech issue and troubleshoot instantly. In his role as an Engineering Lead he has gone beyond his Job Scope and will normally reach out to other in his own department to assist. Having GUS around in the company was fun and with his "slang" it makes us laugh hard at times.<br/><br/>During the years that I have cross path with GUS. I had the opportunity to observe his interpersonal style-he is pleasant and a positive motivator to his fellow team mates and colleagues.',
            person: {
                avatar: "recommendation/daniel-khor.jpeg",
                full_name: "Daniel Khor Chin Huat",
                company: "BeMyGuest - Tours & Activities",
                designation: "Director of Business Development",
            },
            created_at: "2021-10-27",
            updated_at: "2021-10-27",
            featured: 0,
        },
        {
            uuid: "1ca2026d-9d52-4da9-bbe2-5adba175d4c4",
            relation: "Kong worked with Gus in the same team.",
            text: "I have worked with Gus as a fellow Software Engineer since 2017. He is a highly adaptable, encouraging and supportive colleague and an effective team lead.<br/><br/>His software development skill, whether its backend, full stack, is of exceptional high quality. During our stint in the company, he took the time to spearhead some of the initiatives to improve and updating the software development process and applications.<br/><br/>He always has a positive attitude and a desire to produce quality work. Gus is as great a person as he was a colleague, a team lead and his next employer will be lucky to have him.",
            person: {
                avatar: "recommendation/kong-kw.jpg",
                full_name: "Kong KW",
                company: "BeMyGuest - Tours & Activities",
                designation: "Senior Software Engineer",
            },
            created_at: "2021-10-20",
            updated_at: "2021-10-20",
            featured: 0,
        },
        {
            uuid: "99d55cbb-11a4-4fd2-9d5a-1530ef9cb0bb",
            relation: "Wai Min worked with Gus in different teams.",
            text: "I've had the opportunity of knowing Gus for the past. He is always capable of adapting to new working environments. Very positive attitude towards work I definitely would recommend him as full stack web developer.",
            person: {
                avatar: "recommendation/wai-min.jpeg",
                full_name: "Wai Min Ho",
                company: "BeMyGuest - Tours & Activities",
                designation: "Distribution Partnerships Manager",
            },
            created_at: "2020-10-16",
            updated_at: "2020-10-16",
            featured: 0,
        },
        {
            uuid: "baf49d10-1700-4881-9268-5076e80f42f5",
            relation: "Daryle worked with Gus in the same team.",
            text: "I've had the opportunity of knowing Gus for the past. He is always capable of adapting to new working environments. Very positive attitude towards work I definitely would recommend him as full stack web developer.",
            person: {
                avatar: "recommendation/daryle-dale-silva.jpeg",
                full_name: "Daryle Dale De Silva",
                company: "BeMyGuest - Tours & Activities",
                designation: "Senior Full Stack Developer",
            },
            created_at: "2020-01-19",
            updated_at: "2020-01-19",
            featured: 0,
        },
        {
            uuid: "3fb5dfaa-a7b7-411c-8d2e-80b75fcd45df",
            relation: "Dawid managed Gus directly.",
            text: "It was a pleasure to have an opportunity to work with Gustavo. He's a brilliant developer and analyst, with a head full of new ideas. He's not afraid of approaching the most complex problems and testing new waters to find the best solutions.<br/><br/>He's got a great personality and always fun to have around in your team. Always keen to share his knowledge thru training or giving public presentations. He's got that deep internal drive to learn every day and test new ideas in real life, which I always find very valuable.",
            person: {
                avatar: "recommendation/dawid-makowski.jpeg",
                full_name: "Dawid Makowski",
                company: "BeMyGuest - Tours & Activities",
                designation: "CTO",
            },
            created_at: "2019-07-16",
            updated_at: "2019-07-16",
            featured: 1,
        },
        {
            uuid: "045ff8fc-12af-47c7-a761-6c2a0995d352",
            relation: "Jarek managed Gus indirectly",
            text: "Gus has been always committed and eager to learn on professional level plus an exceptional personality when it comes to socializing, which made him a great and valuable team member during our time together at BeMyGuest in Singapore.<br/><br/>Can't recommend enough!",
            person: {
                avatar: "recommendation/jarek-tkaczyk.jpeg",
                full_name: "Jarek Tkaczyk",
                company: "BeMyGuest - Tours & Activities",
                designation: "Tech Lead",
            },
            created_at: "2019-07-11",
            updated_at: "2019-07-11",
            featured: 0,
        },
        {
            uuid: "4784b603-583d-4159-ab6b-7e7bddb4b3e5",
            relation: "Clement managed Gus indirectly",
            text: "Very driven and out of the box thinker, coming up with innovative solutions to complex tech problems! Totally enjoyed having him on the team!",
            person: {
                avatar: "recommendation/clement-wong.jpeg",
                full_name: "Clement Wong",
                company: "BeMyGuest - Tours & Activities",
                designation: "CEO",
            },
            created_at: "2019-06-15",
            updated_at: "2019-06-15",
            featured: 1,
        },
        {
            uuid: "1991f645-d50a-4975-8ba6-90cf18ae3a90",
            relation: "Rudolf worked with Gus in the same team.",
            text: "It is been a real pleasure working together with Gustavo. He's motivated, filled with knowledge, great at public speaking, especially about PHP, Unit Testing or Laravel itself. He worked on biggest projects, properly taking care of the job.<br/><br/>Hard working, responsible and ambitious. Definitely worth recommending.",
            person: {
                avatar: "recommendation/rudolf-ratusiski.jpeg",
                full_name: "Rudolf Ratusiński",
                company: "BeMyGuest - Tours & Activities",
                designation: "Senior DevOps Engineer",
            },
            created_at: "2019-06-14",
            updated_at: "2019-06-14",
            featured: 0,
        },
        {
            uuid: "186c98c0-9df5-42c2-bccd-3724e4f50917",
            relation: "Nabil worked with Gus in different teams.",
            text: "Gustavo is a team player, tech enthusiast with very positive energy.gustavo is one of those colleagues that makes you enjoy working more at the office, he is creative, fast learner and hard worker.",
            person: {
                avatar: "recommendation/nabil-elshafaey.jpeg",
                full_name: "Nabil Elshafaey",
                company: "BeMyGuest - Tours & Activities",
                designation: "Head of Distribution",
            },
            created_at: "2019-06-13",
            updated_at: "2019-06-13",
            featured: 0,
        },
        {
            uuid: "9410aaec-c4fe-4078-ae84-ab2d2dee19d9",
            relation: "Sophie reported directly to Gus.",
            text: "Gus is the one who's really enthusiastic about tech regardless of back-end or front-end. With the pursuit of code quality, he keeps polishing tech skills as well as being very active for code review.<br/><br/>Meanwhile, he enjoys sharing his findings in public and we all benefited a lot from it.",
            person: {
                avatar: "recommendation/sophie-ha.jpeg",
                full_name: "Sophie Ha",
                company: "BeMyGuest - Tours & Activities",
                designation: "Software Engineer",
            },
            created_at: "2019-05-31",
            updated_at: "2019-05-31",
            featured: 0,
        },
        {
            uuid: "d7839355-c7af-4962-bcbd-e7f41a75199c",
            relation: "Sohail worked with Gus in the same team.",
            text: "I'm enjoying a pleasure of working alongside Gustavo for a year now. He has high work ethics and great experience in web technologies to the level that BeMyGuest entrusted him in handling challenging problems (i.e. payment gateways in fragmented South East Asia, API integration, Test Driven Development, Continuous Integration, and Continuous Delivery).<br/><br/>But that is not all, Gustavo regardless of deadline pressure always delivers with a smile. His sense of humor always softens the toughest stressful situations for the rest of the team. \nLong story short he is a true asset to our team.",
            person: {
                avatar: "recommendation/sohail-salehi.jpeg",
                full_name: "Sohail Salehi",
                company: "BeMyGuest - Tours & Activities",
                designation: "Senior Software Engineer",
            },
            created_at: "2018-09-26",
            updated_at: "2018-09-26",
            featured: 0,
        },
        {
            uuid: "0f6dae3e-ec78-43a9-b9ff-322642f88594",
            relation: "Michal worked with Gus in the same team.",
            text: "I had a chance to collaborate with Gustavo for one year, working at one team. He impressed me with his openness and willingness to learn. He dig deeper and deeper in subjects he already knew.<br/><br/>He was also great in sharing that knowledge. Best social skills across all developers I’ve ever meet. Perfect fit to 10xTeam.",
            person: {
                avatar: "recommendation/michal-szymaniak.jpeg",
                full_name: "Michal Szymaniak",
                company: "BeMyGuest - Tours & Activities",
                designation: "Senior Software Engineer",
            },
            created_at: "2018-09-26",
            updated_at: "2018-09-26",
            featured: 0,
        },
        {
            uuid: "387a95d6-d29b-4faf-aa60-3b071c59cd22",
            relation: "Fernando worked with Gus but they were at different companies.",
            text: "I have had the opportunity to work with Gustavo closely and he has demonstrated to be a skilled person. Focus on detail and solid principles. He is a learner by definition and strives for improvement on every step.<br/><br/>Our two projects turned out to be more productive than we forecasted at the beginning of them and I personally can recommend Gustavo as a reliable professional to work with.",
            person: {
                avatar: "recommendation/fernando-rivas.jpeg",
                full_name: "Fernando Rivas",
                company: "Websarrollo - Digital Agency",
                designation: "Senior Software Engineer",
            },
            created_at: "2018-08-30",
            updated_at: "2018-08-30",
            featured: 0,
        },
        {
            uuid: "8e05af84-3054-404f-89f2-428ae69943ef",
            relation: "Jonathan worked with Gus but they were at different companies.",
            text: "Excellent programmer and good project manager with good creative ideas. A good experience to have worked with him.",
            person: {
                avatar: "recommendation/jonathan-trejo.jpeg",
                full_name: "Jonathan Ivan Trejo Zerpa",
                company: "Websarrollo - Digital Agency",
                designation: "Senior Software Engineer",
            },
            created_at: "2018-08-28",
            updated_at: "2018-08-28",
            featured: 0,
        },
        {
            uuid: "4faf4435-93d4-48ef-b980-4b94d353f2f7",
            relation: "Carlos Matute worked with Gus but they were at different companies.",
            text: "I can say that Gustavo had a professional level raising even since we studied at the University. Dedicated, spontaneous, with a very wide resolution of problems and with determination in the solutions due to his high knowledge in the workplace.",
            person: {
                avatar: "recommendation/carlos-matute.jpeg",
                full_name: "Carlos Matute",
                company: "Websarrollo - Digital Agency",
                designation: "Senior Software Engineer",
            },
            created_at: "2018-08-27",
            updated_at: "2018-08-27",
            featured: 0,
        },
        {
            uuid: "50fcd53c-2135-4c94-8fb2-30f111b3218e",
            relation: "Julio Cesar reported directly to Gus.",
            text: "I recommend Gustavo for large projects. He is a professional in the development area very proactive and efficient. It makes use of all the tools available for project management. It is organized and possesses determination and mastery over the development team.",
            person: {
                avatar: "recommendation/julio-cesar.png",
                full_name: "Julio Cesar Hernandez",
                company: "Websarrollo - Digital Agency",
                designation: "Senior Software Engineer",
            },
            created_at: "2018-08-27",
            updated_at: "2018-08-27",
            featured: 0,
        },
        {
            uuid: "b5b4cff9-156e-4296-974e-0c4f0437e31d",
            relation: "Marco work with Gus in the same team.",
            text: "Professional worker, fast learner, enjoyable to work with. Highly analyzer of low level code, always approaching methodology with security first.",
            person: {
                avatar: "recommendation/marco.jpeg",
                full_name: "Marco Gava",
                company: "BeMyGuest - Tours & Activities",
                designation: "Senior Software Engineer",
            },
            created_at: "2018-08-27",
            updated_at: "2018-08-27",
            featured: 0,
        },
    ],
} as const satisfies RecommendationsFixture;
